CREATE TABLE Device (
     id int NOT NULL,
     battery_power DECIMAL,
     blue int,
     clock_speed DECIMAL,
     dual_sim int,
     fc int,
     four_g int,
     int_memory DECIMAL,
     m_dep DECIMAL,
     mobile_wt DECIMAL,
     n_cores DECIMAL,
     pc DECIMAL,
     px_height DECIMAL,
     px_width DECIMAL,
     ram DECIMAL,
     sc_h DECIMAL,
     sc_w DECIMAL,
     talk_time DECIMAL,
     three_g DECIMAL,
     touch_screen int,
     wifi int,
     price_range int,
    PRIMARY KEY (id)
);

